spring:
  datasource:
    url: jdbc:mysql://192.168.80.128/baker?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  redis:
    host: 192.168.80.128
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

#阿里短信发送
ali:
  #ID
  accessKey_id: LTAI5tNYh8zpn7ogsdm4TB8u
  #key
  accessKey_secret: Mbz7otfd6W8N1utu9TDqyyQHh1McpA
  #短信签名名称
  signname: 智能简历分析系统
  #短信模板ID
  templatecode: SMS_276471094
